### ISSUE TITLE
Support for nested folder determine-folder option

### ISSUE THREAD

**Issue by mag382** [fbenz/restdocs-to-postman#16]
https://github.com/fbenz/restdocs-to-postman/pull/17

Our project has a number of endpoints which are nested by their endpoint name grouping.  The secondLastFolder option flattens this out, and the name chosen is not descriptive enough to show its original position in our API.

Therefore a new CLI folder option to maintain the folder and sub-folder structure of our endpoints would be very useful.  

AC:
Pass in --determine-folder nestedFolders in the CLI.
Using the example test data in this project with one extra level, the output in Insomnia/Postman would look like:

![Screen Shot 2019-07-15 at 4 37 58 PM](https://user-images.githubusercontent.com/253305/61247433-0b7bd380-a71f-11e9-9632-a68fb8390340.png)

<img width="501" alt="Screen Shot 2019-07-15 at 4 38 34 PM" src="https://user-images.githubusercontent.com/253305/61247416-0454c580-a71f-11e9-8c80-bb41028595e1.png">

**Comment by fbenz** [comment]
A PR for this will be welcome but it is unlikely that I will invest time into this any time soon.

**Comment by mag382** [comment]
I have this working, but can't push the branch it seems.

**Comment by fbenz** [comment]
If you fork this repository, you can push a branch and then open a pull request against this repository. See https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by mag382** [comment]
Thanks for having a look then.  Really liked how this library worked immediately without any problems.

**Comment by fbenz** [comment]
Support was added in https://github.com/fbenz/restdocs-to-postman/pull/17
