### ISSUE TITLE
unable to convert adoc to postman collection 

### ISSUE THREAD

**Issue by akram85** [fbenz/restdocs-to-postman#37]
Hi @fbenz 
I am unable to convert my  adoc to postman collection.
Please find below the error message , I have also attached the adoc file as well , could you please help me on this ,

Appreciate your support! 

D:\>restdocs-to-postman --input adoc --export-format postman --determine-folder secondLastFolder --output postman-collection.json
C:\Users\Akaram\AppData\Roaming\npm\node_modules\restdocs-to-postman\src\insomnia3-to-postman21.js:86
                path: parsedUrl.pathname.split('/'),
                                         ^

TypeError: Cannot read property 'split' of null
    at toPostmanItem (C:\Users\Akaram\AppData\Roaming\npm\node_modules\←[4mrestdocs-to-postman←[24m\src\insomnia3-to-postman21.js:86:42)
    at C:\Users\Akaram\AppData\Roaming\npm\node_modules\←[4mrestdocs-to-postman←[24m\src\insomnia3-to-postman21.js:174:36
    at Array.forEach (<anonymous>)
    at Object.module.exports.toPostmanCollection (C:\Users\Akaram\AppData\Roaming\npm\node_modules\←[4mrestdocs-to-postman←[24m\src\insomnia3-to-postman21.js:170:10)
    at Object.module.exports.convert (C:\Users\Akaram\AppData\Roaming\npm\node_modules\←[4mrestdocs-to-postman←[24m\src\convert.js:86:53)
    at Object.module.exports.go (C:\Users\Akaram\AppData\Roaming\npm\node_modules\←[4mrestdocs-to-postman←[24m\src\cli.js:45:30)
    at Object.<anonymous> `(C:\Users\Akaram
[curl-request.txt](https://github.com/fbenz/restdocs-to-postman/files/8021590/curl-request.txt)
\AppData\Roaming\npm\node_modules\←[4mrestdocs-to-postman←[24m\bin\cli:3:23)`
←[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:950:32)←[39m

**Comment by fbenz** [comment]
I tested when
```
const url = require('url');
let result = url.parse('<some url>').pathname
```
can be `null` and for this `<some url>` has to be an empty string. As I don't see the attached adoc file, I can't tell which issue caused the URL to not be read correctly.

**Comment by akram85** [comment]
Hi @fbenz  ,
Thanks for the response 
Please find below the adoc file content , upload of file somehow did not work here .

= Member API Docs

== GET
Get all members

/member

HTTP Request:
[source,http,options="nowrap"]
----
GET /member HTTP/1.1
Host: localhost:8080

----
HTTP Response:
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 236

[ {
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}, {
  "id" : 1,
  "firstName" : "first name",
  "lastName" : "last name"
}, {
  "id" : 2,
  "firstName" : "first name",
  "lastName" : "last name"
} ]
----
curl Request:
[source,bash]
----
$ curl 'http://localhost:8080/member' -i -X GET
----
Request body:
[source,options="nowrap"]
----

----
Response body:
[source,options="nowrap"]
----
[ {
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}, {
  "id" : 1,
  "firstName" : "first name",
  "lastName" : "last name"
}, {
  "id" : 2,
  "firstName" : "first name",
  "lastName" : "last name"
} ]
----

== GET

Get member by ID

/member/{id}

HTTP Request:
[source,http,options="nowrap"]
----
GET /member/0 HTTP/1.1
Host: localhost:8080

----
HTTP Response:
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 76

{
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}
----
curl Request:
[source,bash]
----
$ curl 'http://localhost:8080/member/0' -i -X GET
----
Request body:
[source,options="nowrap"]
----

----
Response body:
[source,options="nowrap"]
----
{
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}
----

== POST

Create a member

/member

HTTP Request:
[source,http,options="nowrap"]
----
POST /member HTTP/1.1
Content-Type: application/json
Content-Length: 76
Host: localhost:8080

{
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}
----
HTTP Response:
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 76

{
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}
----
curl Request:
[source,bash]
----
$ curl 'http://localhost:8080/member' -i -X POST \
    -H 'Content-Type: application/json' \
    -d '{
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}'
----
Request body:
[source,options="nowrap"]
----
{
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}
----
Response body:
[source,options="nowrap"]
----
{
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}
----

== PUT

Update member

/member

HTTP Request:
[source,http,options="nowrap"]
----
PUT /member HTTP/1.1
Content-Type: application/json
Content-Length: 76
Host: localhost:8080

{
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}
----
HTTP Response:
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 76

{
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}
----
curl Request:
[source,bash]
----
$ curl 'http://localhost:8080/member' -i -X PUT \
    -H 'Content-Type: application/json' \
    -d '{
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}'
----
Request body:
[source,options="nowrap"]
----
{
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}
----
Response body:
[source,options="nowrap"]
----
{
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}
----

== DELETE

Delete a member

/member

HTTP Request:
[source,http,options="nowrap"]
----
DELETE /member/0 HTTP/1.1
Host: localhost:8080

----
HTTP Response:
[source,http,options="nowrap"]
----
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 76

{
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}
----
curl Request:
[source,bash]
----
$ curl 'http://localhost:8080/member/0' -i -X DELETE
----
Request body:
[source,options="nowrap"]
----

----
Response body:
[source,options="nowrap"]
----
{
  "id" : 0,
  "firstName" : "first name",
  "lastName" : "last name"
}
----
